export const API = {
  DASHBOARD_GEO: '/dashboard/geo-distribution',
  DASHBOARD_TIMELINE: '/dashboard/timeline',
  DASHBOARD_PIE: '/dashboard/country-pie',
  DASHBOARD_AMR: '/dashboard/amr-stats',
  DASHBOARD_VF: '/dashboard/vf-stats',
  DASHBOARD_ATTRS: '/dashboard/attribute-stats',
  SAMPLE_LIST: '/samples',
  SAMPLE_DETAIL: (id: string) => `/samples/${id}`,
  TYPING_MLST: '/typing/mlst',
  TYPING_MLST_PIE: '/typing/mlst/pie-chart',
  TYPING_CGMLST: '/typing/cgmlst',
  TYPING_ANTIGEN: '/typing/antigen',
  AMR_MATRIX: '/amr/matrix',
  AMR_STATS: '/amr/stats',
  AMR_CLASSES: '/amr/classes',
  VF_MATRIX: '/vf/matrix',
  VF_STATS: '/vf/stats',
  VF_CATEGORIES: '/vf/categories',
  TREE_DATA: '/tree-heatmap/data',
  TREE_CONFIG: '/tree-heatmap/config',
} as const
